[package]
name = "mlws_web"
version = "0.1.0"
authors = ["ThePerkinrex <theperkinrex@gmail.com>"]
edition = "2018"


[dependencies]
actix-web = "2.0.0"
actix-rt = "1.1.1"
tera = {version = "1.5.0", default-features = false}
lazy_static = "1.4.0"
serde = "1.0.115"

mlws_lib = {path = "./mlws_lib"}